apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-login
spec:
  selector:
    matchLabels:
      app: go-login
  replicas: 2
  template:
    metadata:
      labels:
        app: go-login
    spec:
      containers:
      - name: go-login
        image: ghcr.io/samer955/go-login-cicd:1.0.3
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-login-service
spec:
  type: NodePort
  selector:
    app: go-login
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32323
